
'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.ComponentModel
Imports System.Data.EntityClient
Imports System.Data.Objects
Imports System.Data.Objects.DataClasses
Imports System.Linq
Imports System.Runtime.Serialization
Imports System.Xml.Serialization


<Assembly: EdmSchemaAttribute("2835a36d-ff80-4225-8b10-00fd19419d84")>
#Region "EDM Relationship Metadata"
<Assembly: EdmRelationshipAttribute("MyScout2015DBModel", "FK_EventsTableMatchTable", "EventsTable", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(EventsTable), "MatchTable", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(MatchTable), True)>
<Assembly: EdmRelationshipAttribute("MyScout2015DBModel", "FK_EventsTableScoresTable", "EventsTable", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(EventsTable), "ScoresTable", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(ScoresTable), True)>
<Assembly: EdmRelationshipAttribute("MyScout2015DBModel", "FK_EventsTableTeamTotalsTable", "EventsTable", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(EventsTable), "TeamTotalsTable", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(TeamTotalsTable), True)>

#End Region

#Region "Contexts"

''' <summary>
''' No Metadata Documentation available.
''' </summary>
Public Partial Class MyScout2015DBEntities
    Inherits ObjectContext

    #Region "Constructors"

    ''' <summary>
    ''' Initializes a new MyScout2015DBEntities object using the connection string found in the 'MyScout2015DBEntities' section of the application configuration file.
    ''' </summary>
    Public Sub New()
        MyBase.New("name=MyScout2015DBEntities", "MyScout2015DBEntities")
        MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialize a new MyScout2015DBEntities object.
    ''' </summary>
    Public Sub New(ByVal connectionString As String)
        MyBase.New(connectionString, "MyScout2015DBEntities")
        MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialize a new MyScout2015DBEntities object.
    ''' </summary>
    Public Sub New(ByVal connection As EntityConnection)
        MyBase.New(connection, "MyScout2015DBEntities")
        MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    #End Region

    #Region "Partial Methods"

    Partial Private Sub OnContextCreated()
    End Sub

    #End Region

    #Region "ObjectSet Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property EventsTables() As ObjectSet(Of EventsTable)
        Get
            If (_EventsTables Is Nothing) Then
                _EventsTables = MyBase.CreateObjectSet(Of EventsTable)("EventsTables")
            End If
            Return _EventsTables
        End Get
    End Property

    Private _EventsTables As ObjectSet(Of EventsTable)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property MatchTables() As ObjectSet(Of MatchTable)
        Get
            If (_MatchTables Is Nothing) Then
                _MatchTables = MyBase.CreateObjectSet(Of MatchTable)("MatchTables")
            End If
            Return _MatchTables
        End Get
    End Property

    Private _MatchTables As ObjectSet(Of MatchTable)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property ScoresTables() As ObjectSet(Of ScoresTable)
        Get
            If (_ScoresTables Is Nothing) Then
                _ScoresTables = MyBase.CreateObjectSet(Of ScoresTable)("ScoresTables")
            End If
            Return _ScoresTables
        End Get
    End Property

    Private _ScoresTables As ObjectSet(Of ScoresTable)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property TeamTotalsTables() As ObjectSet(Of TeamTotalsTable)
        Get
            If (_TeamTotalsTables Is Nothing) Then
                _TeamTotalsTables = MyBase.CreateObjectSet(Of TeamTotalsTable)("TeamTotalsTables")
            End If
            Return _TeamTotalsTables
        End Get
    End Property

    Private _TeamTotalsTables As ObjectSet(Of TeamTotalsTable)

    #End Region

    #Region "AddTo Methods"

    ''' <summary>
    ''' Deprecated Method for adding a new object to the EventsTables EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToEventsTables(ByVal eventsTable As EventsTable)
        MyBase.AddObject("EventsTables", eventsTable)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the MatchTables EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToMatchTables(ByVal matchTable As MatchTable)
        MyBase.AddObject("MatchTables", matchTable)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the ScoresTables EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToScoresTables(ByVal scoresTable As ScoresTable)
        MyBase.AddObject("ScoresTables", scoresTable)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the TeamTotalsTables EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToTeamTotalsTables(ByVal teamTotalsTable As TeamTotalsTable)
        MyBase.AddObject("TeamTotalsTables", teamTotalsTable)
    End Sub

    #End Region

End Class

#End Region

#Region "Entities"

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="MyScout2015DBModel", Name:="EventsTable")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class EventsTable
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new EventsTable object.
    ''' </summary>
    ''' <param name="event">Initial value of the Event property.</param>
    ''' <param name="teamCount">Initial value of the TeamCount property.</param>
    ''' <param name="matchCount">Initial value of the MatchCount property.</param>
    ''' <param name="matchesComplete">Initial value of the MatchesComplete property.</param>
    ''' <param name="isFavorite">Initial value of the isFavorite property.</param>
    Public Shared Function CreateEventsTable([event] As Global.System.String, teamCount As Global.System.Int16, matchCount As Global.System.Int16, matchesComplete As Global.System.Int16, isFavorite As Global.System.Boolean) As EventsTable
        Dim eventsTable as EventsTable = New EventsTable
        eventsTable.[Event] = [event]
        eventsTable.TeamCount = teamCount
        eventsTable.MatchCount = matchCount
        eventsTable.MatchesComplete = matchesComplete
        eventsTable.isFavorite = isFavorite
        Return eventsTable
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property [Event]() As Global.System.String
        Get
            Return _Event
        End Get
        Set
            If (_Event <> Value) Then
                OnEventChanging(value)
                ReportPropertyChanging("Event")
                _Event = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("Event")
                OnEventChanged()
            End If
        End Set
    End Property

    Private _Event As Global.System.String
    Private Partial Sub OnEventChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnEventChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property AccessDate() As Nullable(Of Global.System.DateTime)
        Get
            Return _AccessDate
        End Get
        Set
            OnAccessDateChanging(value)
            ReportPropertyChanging("AccessDate")
            _AccessDate = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("AccessDate")
            OnAccessDateChanged()
        End Set
    End Property

    Private _AccessDate As Nullable(Of Global.System.DateTime)
    Private Partial Sub OnAccessDateChanging(value As Nullable(Of Global.System.DateTime))
    End Sub

    Private Partial Sub OnAccessDateChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property TeamCount() As Global.System.Int16
        Get
            Return _TeamCount
        End Get
        Set
            OnTeamCountChanging(value)
            ReportPropertyChanging("TeamCount")
            _TeamCount = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("TeamCount")
            OnTeamCountChanged()
        End Set
    End Property

    Private _TeamCount As Global.System.Int16
    Private Partial Sub OnTeamCountChanging(value As Global.System.Int16)
    End Sub

    Private Partial Sub OnTeamCountChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property MatchCount() As Global.System.Int16
        Get
            Return _MatchCount
        End Get
        Set
            OnMatchCountChanging(value)
            ReportPropertyChanging("MatchCount")
            _MatchCount = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("MatchCount")
            OnMatchCountChanged()
        End Set
    End Property

    Private _MatchCount As Global.System.Int16
    Private Partial Sub OnMatchCountChanging(value As Global.System.Int16)
    End Sub

    Private Partial Sub OnMatchCountChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property MatchesComplete() As Global.System.Int16
        Get
            Return _MatchesComplete
        End Get
        Set
            OnMatchesCompleteChanging(value)
            ReportPropertyChanging("MatchesComplete")
            _MatchesComplete = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("MatchesComplete")
            OnMatchesCompleteChanged()
        End Set
    End Property

    Private _MatchesComplete As Global.System.Int16
    Private Partial Sub OnMatchesCompleteChanging(value As Global.System.Int16)
    End Sub

    Private Partial Sub OnMatchesCompleteChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property isFavorite() As Global.System.Boolean
        Get
            Return _isFavorite
        End Get
        Set
            OnisFavoriteChanging(value)
            ReportPropertyChanging("isFavorite")
            _isFavorite = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("isFavorite")
            OnisFavoriteChanged()
        End Set
    End Property

    Private _isFavorite As Global.System.Boolean
    Private Partial Sub OnisFavoriteChanging(value As Global.System.Boolean)
    End Sub

    Private Partial Sub OnisFavoriteChanged()
    End Sub

    #End Region

    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("MyScout2015DBModel", "FK_EventsTableMatchTable", "MatchTable")>
     Public Property MatchTables() As EntityCollection(Of MatchTable)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of MatchTable)("MyScout2015DBModel.FK_EventsTableMatchTable", "MatchTable")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of MatchTable)("MyScout2015DBModel.FK_EventsTableMatchTable", "MatchTable", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("MyScout2015DBModel", "FK_EventsTableScoresTable", "ScoresTable")>
     Public Property ScoresTables() As EntityCollection(Of ScoresTable)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of ScoresTable)("MyScout2015DBModel.FK_EventsTableScoresTable", "ScoresTable")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of ScoresTable)("MyScout2015DBModel.FK_EventsTableScoresTable", "ScoresTable", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("MyScout2015DBModel", "FK_EventsTableTeamTotalsTable", "TeamTotalsTable")>
     Public Property TeamTotalsTables() As EntityCollection(Of TeamTotalsTable)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of TeamTotalsTable)("MyScout2015DBModel.FK_EventsTableTeamTotalsTable", "TeamTotalsTable")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of TeamTotalsTable)("MyScout2015DBModel.FK_EventsTableTeamTotalsTable", "TeamTotalsTable", value)
            End If
        End Set
    End Property

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="MyScout2015DBModel", Name:="MatchTable")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class MatchTable
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new MatchTable object.
    ''' </summary>
    ''' <param name="event">Initial value of the Event property.</param>
    ''' <param name="match">Initial value of the Match property.</param>
    ''' <param name="red1">Initial value of the Red1 property.</param>
    ''' <param name="red2">Initial value of the Red2 property.</param>
    ''' <param name="red3">Initial value of the Red3 property.</param>
    ''' <param name="blue1">Initial value of the Blue1 property.</param>
    ''' <param name="blue2">Initial value of the Blue2 property.</param>
    ''' <param name="blue3">Initial value of the Blue3 property.</param>
    Public Shared Function CreateMatchTable([event] As Global.System.String, match As Global.System.Int16, red1 As Global.System.Int16, red2 As Global.System.Int16, red3 As Global.System.Int16, blue1 As Global.System.Int16, blue2 As Global.System.Int16, blue3 As Global.System.Int16) As MatchTable
        Dim matchTable as MatchTable = New MatchTable
        matchTable.[Event] = [event]
        matchTable.Match = match
        matchTable.Red1 = red1
        matchTable.Red2 = red2
        matchTable.Red3 = red3
        matchTable.Blue1 = blue1
        matchTable.Blue2 = blue2
        matchTable.Blue3 = blue3
        Return matchTable
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property [Event]() As Global.System.String
        Get
            Return _Event
        End Get
        Set
            If (_Event <> Value) Then
                OnEventChanging(value)
                ReportPropertyChanging("Event")
                _Event = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("Event")
                OnEventChanged()
            End If
        End Set
    End Property

    Private _Event As Global.System.String
    Private Partial Sub OnEventChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnEventChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Match() As Global.System.Int16
        Get
            Return _Match
        End Get
        Set
            If (_Match <> Value) Then
                OnMatchChanging(value)
                ReportPropertyChanging("Match")
                _Match = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("Match")
                OnMatchChanged()
            End If
        End Set
    End Property

    Private _Match As Global.System.Int16
    Private Partial Sub OnMatchChanging(value As Global.System.Int16)
    End Sub

    Private Partial Sub OnMatchChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Red1() As Global.System.Int16
        Get
            Return _Red1
        End Get
        Set
            OnRed1Changing(value)
            ReportPropertyChanging("Red1")
            _Red1 = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("Red1")
            OnRed1Changed()
        End Set
    End Property

    Private _Red1 As Global.System.Int16
    Private Partial Sub OnRed1Changing(value As Global.System.Int16)
    End Sub

    Private Partial Sub OnRed1Changed()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Red2() As Global.System.Int16
        Get
            Return _Red2
        End Get
        Set
            OnRed2Changing(value)
            ReportPropertyChanging("Red2")
            _Red2 = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("Red2")
            OnRed2Changed()
        End Set
    End Property

    Private _Red2 As Global.System.Int16
    Private Partial Sub OnRed2Changing(value As Global.System.Int16)
    End Sub

    Private Partial Sub OnRed2Changed()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Red3() As Global.System.Int16
        Get
            Return _Red3
        End Get
        Set
            OnRed3Changing(value)
            ReportPropertyChanging("Red3")
            _Red3 = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("Red3")
            OnRed3Changed()
        End Set
    End Property

    Private _Red3 As Global.System.Int16
    Private Partial Sub OnRed3Changing(value As Global.System.Int16)
    End Sub

    Private Partial Sub OnRed3Changed()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Blue1() As Global.System.Int16
        Get
            Return _Blue1
        End Get
        Set
            OnBlue1Changing(value)
            ReportPropertyChanging("Blue1")
            _Blue1 = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("Blue1")
            OnBlue1Changed()
        End Set
    End Property

    Private _Blue1 As Global.System.Int16
    Private Partial Sub OnBlue1Changing(value As Global.System.Int16)
    End Sub

    Private Partial Sub OnBlue1Changed()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Blue2() As Global.System.Int16
        Get
            Return _Blue2
        End Get
        Set
            OnBlue2Changing(value)
            ReportPropertyChanging("Blue2")
            _Blue2 = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("Blue2")
            OnBlue2Changed()
        End Set
    End Property

    Private _Blue2 As Global.System.Int16
    Private Partial Sub OnBlue2Changing(value As Global.System.Int16)
    End Sub

    Private Partial Sub OnBlue2Changed()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Blue3() As Global.System.Int16
        Get
            Return _Blue3
        End Get
        Set
            OnBlue3Changing(value)
            ReportPropertyChanging("Blue3")
            _Blue3 = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("Blue3")
            OnBlue3Changed()
        End Set
    End Property

    Private _Blue3 As Global.System.Int16
    Private Partial Sub OnBlue3Changing(value As Global.System.Int16)
    End Sub

    Private Partial Sub OnBlue3Changed()
    End Sub

    #End Region

    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("MyScout2015DBModel", "FK_EventsTableMatchTable", "EventsTable")>
    Public Property EventsTable() As EventsTable
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of EventsTable)("MyScout2015DBModel.FK_EventsTableMatchTable", "EventsTable").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of EventsTable)("MyScout2015DBModel.FK_EventsTableMatchTable", "EventsTable").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property EventsTableReference() As EntityReference(Of EventsTable)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of EventsTable)("MyScout2015DBModel.FK_EventsTableMatchTable", "EventsTable")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of EventsTable)("MyScout2015DBModel.FK_EventsTableMatchTable", "EventsTable", value)
            End If
        End Set
    End Property

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="MyScout2015DBModel", Name:="ScoresTable")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class ScoresTable
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new ScoresTable object.
    ''' </summary>
    ''' <param name="event">Initial value of the Event property.</param>
    ''' <param name="match">Initial value of the Match property.</param>
    ''' <param name="team">Initial value of the Team property.</param>
    ''' <param name="autoTotes">Initial value of the AutoTotes property.</param>
    ''' <param name="autoContainersMoved">Initial value of the AutoContainersMoved property.</param>
    ''' <param name="toteScoreCount">Initial value of the ToteScoreCount property.</param>
    ''' <param name="binsStacked">Initial value of the BinsStacked property.</param>
    ''' <param name="autoMobility">Initial value of the AutoMobility property.</param>
    ''' <param name="didFail">Initial value of the DidFail property.</param>
    ''' <param name="knockdownCount">Initial value of the KnockdownCount property.</param>
    ''' <param name="landfillLitterCount">Initial value of the LandfillLitterCount property.</param>
    ''' <param name="recycledLitterCount">Initial value of the RecycledLitterCount property.</param>
    Public Shared Function CreateScoresTable([event] As Global.System.String, match As Global.System.Int16, team As Global.System.Int16, autoTotes As Global.System.String, autoContainersMoved As Global.System.Int16, toteScoreCount As Global.System.Int16, binsStacked As Global.System.String, autoMobility As Global.System.Int16, didFail As Global.System.Boolean, knockdownCount As Global.System.Int16, landfillLitterCount As Global.System.Int16, recycledLitterCount As Global.System.Int16) As ScoresTable
        Dim scoresTable as ScoresTable = New ScoresTable
        scoresTable.[Event] = [event]
        scoresTable.Match = match
        scoresTable.Team = team
        scoresTable.AutoTotes = autoTotes
        scoresTable.AutoContainersMoved = autoContainersMoved
        scoresTable.ToteScoreCount = toteScoreCount
        scoresTable.BinsStacked = binsStacked
        scoresTable.AutoMobility = autoMobility
        scoresTable.DidFail = didFail
        scoresTable.KnockdownCount = knockdownCount
        scoresTable.LandfillLitterCount = landfillLitterCount
        scoresTable.RecycledLitterCount = recycledLitterCount
        Return scoresTable
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property [Event]() As Global.System.String
        Get
            Return _Event
        End Get
        Set
            If (_Event <> Value) Then
                OnEventChanging(value)
                ReportPropertyChanging("Event")
                _Event = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("Event")
                OnEventChanged()
            End If
        End Set
    End Property

    Private _Event As Global.System.String
    Private Partial Sub OnEventChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnEventChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Match() As Global.System.Int16
        Get
            Return _Match
        End Get
        Set
            If (_Match <> Value) Then
                OnMatchChanging(value)
                ReportPropertyChanging("Match")
                _Match = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("Match")
                OnMatchChanged()
            End If
        End Set
    End Property

    Private _Match As Global.System.Int16
    Private Partial Sub OnMatchChanging(value As Global.System.Int16)
    End Sub

    Private Partial Sub OnMatchChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Team() As Global.System.Int16
        Get
            Return _Team
        End Get
        Set
            If (_Team <> Value) Then
                OnTeamChanging(value)
                ReportPropertyChanging("Team")
                _Team = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("Team")
                OnTeamChanged()
            End If
        End Set
    End Property

    Private _Team As Global.System.Int16
    Private Partial Sub OnTeamChanging(value As Global.System.Int16)
    End Sub

    Private Partial Sub OnTeamChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property AutoTotes() As Global.System.String
        Get
            Return _AutoTotes
        End Get
        Set
            OnAutoTotesChanging(value)
            ReportPropertyChanging("AutoTotes")
            _AutoTotes = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("AutoTotes")
            OnAutoTotesChanged()
        End Set
    End Property

    Private _AutoTotes As Global.System.String
    Private Partial Sub OnAutoTotesChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnAutoTotesChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property AutoContainersMoved() As Global.System.Int16
        Get
            Return _AutoContainersMoved
        End Get
        Set
            OnAutoContainersMovedChanging(value)
            ReportPropertyChanging("AutoContainersMoved")
            _AutoContainersMoved = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("AutoContainersMoved")
            OnAutoContainersMovedChanged()
        End Set
    End Property

    Private _AutoContainersMoved As Global.System.Int16
    Private Partial Sub OnAutoContainersMovedChanging(value As Global.System.Int16)
    End Sub

    Private Partial Sub OnAutoContainersMovedChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property ToteScoreCount() As Global.System.Int16
        Get
            Return _ToteScoreCount
        End Get
        Set
            OnToteScoreCountChanging(value)
            ReportPropertyChanging("ToteScoreCount")
            _ToteScoreCount = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("ToteScoreCount")
            OnToteScoreCountChanged()
        End Set
    End Property

    Private _ToteScoreCount As Global.System.Int16
    Private Partial Sub OnToteScoreCountChanging(value As Global.System.Int16)
    End Sub

    Private Partial Sub OnToteScoreCountChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property BinsStacked() As Global.System.String
        Get
            Return _BinsStacked
        End Get
        Set
            OnBinsStackedChanging(value)
            ReportPropertyChanging("BinsStacked")
            _BinsStacked = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("BinsStacked")
            OnBinsStackedChanged()
        End Set
    End Property

    Private _BinsStacked As Global.System.String
    Private Partial Sub OnBinsStackedChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnBinsStackedChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property AutoMobility() As Global.System.Int16
        Get
            Return _AutoMobility
        End Get
        Set
            OnAutoMobilityChanging(value)
            ReportPropertyChanging("AutoMobility")
            _AutoMobility = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("AutoMobility")
            OnAutoMobilityChanged()
        End Set
    End Property

    Private _AutoMobility As Global.System.Int16
    Private Partial Sub OnAutoMobilityChanging(value As Global.System.Int16)
    End Sub

    Private Partial Sub OnAutoMobilityChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property DidFail() As Global.System.Boolean
        Get
            Return _DidFail
        End Get
        Set
            OnDidFailChanging(value)
            ReportPropertyChanging("DidFail")
            _DidFail = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("DidFail")
            OnDidFailChanged()
        End Set
    End Property

    Private _DidFail As Global.System.Boolean
    Private Partial Sub OnDidFailChanging(value As Global.System.Boolean)
    End Sub

    Private Partial Sub OnDidFailChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property KnockdownCount() As Global.System.Int16
        Get
            Return _KnockdownCount
        End Get
        Set
            OnKnockdownCountChanging(value)
            ReportPropertyChanging("KnockdownCount")
            _KnockdownCount = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("KnockdownCount")
            OnKnockdownCountChanged()
        End Set
    End Property

    Private _KnockdownCount As Global.System.Int16
    Private Partial Sub OnKnockdownCountChanging(value As Global.System.Int16)
    End Sub

    Private Partial Sub OnKnockdownCountChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property LandfillLitterCount() As Global.System.Int16
        Get
            Return _LandfillLitterCount
        End Get
        Set
            OnLandfillLitterCountChanging(value)
            ReportPropertyChanging("LandfillLitterCount")
            _LandfillLitterCount = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("LandfillLitterCount")
            OnLandfillLitterCountChanged()
        End Set
    End Property

    Private _LandfillLitterCount As Global.System.Int16
    Private Partial Sub OnLandfillLitterCountChanging(value As Global.System.Int16)
    End Sub

    Private Partial Sub OnLandfillLitterCountChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property RecycledLitterCount() As Global.System.Int16
        Get
            Return _RecycledLitterCount
        End Get
        Set
            OnRecycledLitterCountChanging(value)
            ReportPropertyChanging("RecycledLitterCount")
            _RecycledLitterCount = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("RecycledLitterCount")
            OnRecycledLitterCountChanged()
        End Set
    End Property

    Private _RecycledLitterCount As Global.System.Int16
    Private Partial Sub OnRecycledLitterCountChanging(value As Global.System.Int16)
    End Sub

    Private Partial Sub OnRecycledLitterCountChanged()
    End Sub

    #End Region

    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("MyScout2015DBModel", "FK_EventsTableScoresTable", "EventsTable")>
    Public Property EventsTable() As EventsTable
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of EventsTable)("MyScout2015DBModel.FK_EventsTableScoresTable", "EventsTable").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of EventsTable)("MyScout2015DBModel.FK_EventsTableScoresTable", "EventsTable").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property EventsTableReference() As EntityReference(Of EventsTable)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of EventsTable)("MyScout2015DBModel.FK_EventsTableScoresTable", "EventsTable")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of EventsTable)("MyScout2015DBModel.FK_EventsTableScoresTable", "EventsTable", value)
            End If
        End Set
    End Property

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="MyScout2015DBModel", Name:="TeamTotalsTable")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class TeamTotalsTable
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new TeamTotalsTable object.
    ''' </summary>
    ''' <param name="event">Initial value of the Event property.</param>
    ''' <param name="team">Initial value of the Team property.</param>
    ''' <param name="autoToteTotal">Initial value of the AutoToteTotal property.</param>
    ''' <param name="autoTotalContainers">Initial value of the AutoTotalContainers property.</param>
    ''' <param name="autoMobilityTotal">Initial value of the AutoMobilityTotal property.</param>
    ''' <param name="toteScoreCountTotal">Initial value of the ToteScoreCountTotal property.</param>
    ''' <param name="binsStackedTotal">Initial value of the BinsStackedTotal property.</param>
    ''' <param name="failTotal">Initial value of the FailTotal property.</param>
    ''' <param name="knockdownTotal">Initial value of the KnockdownTotal property.</param>
    ''' <param name="autoComments">Initial value of the AutoComments property.</param>
    ''' <param name="otherComments">Initial value of the OtherComments property.</param>
    ''' <param name="toteReachHeight">Initial value of the ToteReachHeight property.</param>
    ''' <param name="binReachHeight">Initial value of the BinReachHeight property.</param>
    ''' <param name="teamName">Initial value of the TeamName property.</param>
    ''' <param name="runs">Initial value of the Runs property.</param>
    ''' <param name="landfillLitterTotal">Initial value of the LandfillLitterTotal property.</param>
    ''' <param name="recycledLitterTotal">Initial value of the RecycledLitterTotal property.</param>
    Public Shared Function CreateTeamTotalsTable([event] As Global.System.String, team As Global.System.Int16, autoToteTotal As Global.System.Int16, autoTotalContainers As Global.System.Int16, autoMobilityTotal As Global.System.Int16, toteScoreCountTotal As Global.System.Int16, binsStackedTotal As Global.System.Int16, failTotal As Global.System.Int16, knockdownTotal As Global.System.String, autoComments As Global.System.String, otherComments As Global.System.String, toteReachHeight As Global.System.Int16, binReachHeight As Global.System.Int16, teamName As Global.System.String, runs As Global.System.Int16, landfillLitterTotal As Global.System.String, recycledLitterTotal As Global.System.Int16) As TeamTotalsTable
        Dim teamTotalsTable as TeamTotalsTable = New TeamTotalsTable
        teamTotalsTable.[Event] = [event]
        teamTotalsTable.Team = team
        teamTotalsTable.AutoToteTotal = autoToteTotal
        teamTotalsTable.AutoTotalContainers = autoTotalContainers
        teamTotalsTable.AutoMobilityTotal = autoMobilityTotal
        teamTotalsTable.ToteScoreCountTotal = toteScoreCountTotal
        teamTotalsTable.BinsStackedTotal = binsStackedTotal
        teamTotalsTable.FailTotal = failTotal
        teamTotalsTable.KnockdownTotal = knockdownTotal
        teamTotalsTable.AutoComments = autoComments
        teamTotalsTable.OtherComments = otherComments
        teamTotalsTable.ToteReachHeight = toteReachHeight
        teamTotalsTable.BinReachHeight = binReachHeight
        teamTotalsTable.TeamName = teamName
        teamTotalsTable.Runs = runs
        teamTotalsTable.LandfillLitterTotal = landfillLitterTotal
        teamTotalsTable.RecycledLitterTotal = recycledLitterTotal
        Return teamTotalsTable
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property [Event]() As Global.System.String
        Get
            Return _Event
        End Get
        Set
            If (_Event <> Value) Then
                OnEventChanging(value)
                ReportPropertyChanging("Event")
                _Event = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("Event")
                OnEventChanged()
            End If
        End Set
    End Property

    Private _Event As Global.System.String
    Private Partial Sub OnEventChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnEventChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Team() As Global.System.Int16
        Get
            Return _Team
        End Get
        Set
            If (_Team <> Value) Then
                OnTeamChanging(value)
                ReportPropertyChanging("Team")
                _Team = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("Team")
                OnTeamChanged()
            End If
        End Set
    End Property

    Private _Team As Global.System.Int16
    Private Partial Sub OnTeamChanging(value As Global.System.Int16)
    End Sub

    Private Partial Sub OnTeamChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property AutoToteTotal() As Global.System.Int16
        Get
            Return _AutoToteTotal
        End Get
        Set
            OnAutoToteTotalChanging(value)
            ReportPropertyChanging("AutoToteTotal")
            _AutoToteTotal = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("AutoToteTotal")
            OnAutoToteTotalChanged()
        End Set
    End Property

    Private _AutoToteTotal As Global.System.Int16
    Private Partial Sub OnAutoToteTotalChanging(value As Global.System.Int16)
    End Sub

    Private Partial Sub OnAutoToteTotalChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property AutoTotalContainers() As Global.System.Int16
        Get
            Return _AutoTotalContainers
        End Get
        Set
            OnAutoTotalContainersChanging(value)
            ReportPropertyChanging("AutoTotalContainers")
            _AutoTotalContainers = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("AutoTotalContainers")
            OnAutoTotalContainersChanged()
        End Set
    End Property

    Private _AutoTotalContainers As Global.System.Int16
    Private Partial Sub OnAutoTotalContainersChanging(value As Global.System.Int16)
    End Sub

    Private Partial Sub OnAutoTotalContainersChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property AutoMobilityTotal() As Global.System.Int16
        Get
            Return _AutoMobilityTotal
        End Get
        Set
            OnAutoMobilityTotalChanging(value)
            ReportPropertyChanging("AutoMobilityTotal")
            _AutoMobilityTotal = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("AutoMobilityTotal")
            OnAutoMobilityTotalChanged()
        End Set
    End Property

    Private _AutoMobilityTotal As Global.System.Int16
    Private Partial Sub OnAutoMobilityTotalChanging(value As Global.System.Int16)
    End Sub

    Private Partial Sub OnAutoMobilityTotalChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property ToteScoreCountTotal() As Global.System.Int16
        Get
            Return _ToteScoreCountTotal
        End Get
        Set
            OnToteScoreCountTotalChanging(value)
            ReportPropertyChanging("ToteScoreCountTotal")
            _ToteScoreCountTotal = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("ToteScoreCountTotal")
            OnToteScoreCountTotalChanged()
        End Set
    End Property

    Private _ToteScoreCountTotal As Global.System.Int16
    Private Partial Sub OnToteScoreCountTotalChanging(value As Global.System.Int16)
    End Sub

    Private Partial Sub OnToteScoreCountTotalChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property BinsStackedTotal() As Global.System.Int16
        Get
            Return _BinsStackedTotal
        End Get
        Set
            OnBinsStackedTotalChanging(value)
            ReportPropertyChanging("BinsStackedTotal")
            _BinsStackedTotal = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("BinsStackedTotal")
            OnBinsStackedTotalChanged()
        End Set
    End Property

    Private _BinsStackedTotal As Global.System.Int16
    Private Partial Sub OnBinsStackedTotalChanging(value As Global.System.Int16)
    End Sub

    Private Partial Sub OnBinsStackedTotalChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property FailTotal() As Global.System.Int16
        Get
            Return _FailTotal
        End Get
        Set
            OnFailTotalChanging(value)
            ReportPropertyChanging("FailTotal")
            _FailTotal = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("FailTotal")
            OnFailTotalChanged()
        End Set
    End Property

    Private _FailTotal As Global.System.Int16
    Private Partial Sub OnFailTotalChanging(value As Global.System.Int16)
    End Sub

    Private Partial Sub OnFailTotalChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property KnockdownTotal() As Global.System.String
        Get
            Return _KnockdownTotal
        End Get
        Set
            OnKnockdownTotalChanging(value)
            ReportPropertyChanging("KnockdownTotal")
            _KnockdownTotal = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("KnockdownTotal")
            OnKnockdownTotalChanged()
        End Set
    End Property

    Private _KnockdownTotal As Global.System.String
    Private Partial Sub OnKnockdownTotalChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnKnockdownTotalChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property AutoComments() As Global.System.String
        Get
            Return _AutoComments
        End Get
        Set
            OnAutoCommentsChanging(value)
            ReportPropertyChanging("AutoComments")
            _AutoComments = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("AutoComments")
            OnAutoCommentsChanged()
        End Set
    End Property

    Private _AutoComments As Global.System.String
    Private Partial Sub OnAutoCommentsChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnAutoCommentsChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property OtherComments() As Global.System.String
        Get
            Return _OtherComments
        End Get
        Set
            OnOtherCommentsChanging(value)
            ReportPropertyChanging("OtherComments")
            _OtherComments = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("OtherComments")
            OnOtherCommentsChanged()
        End Set
    End Property

    Private _OtherComments As Global.System.String
    Private Partial Sub OnOtherCommentsChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnOtherCommentsChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property ToteReachHeight() As Global.System.Int16
        Get
            Return _ToteReachHeight
        End Get
        Set
            OnToteReachHeightChanging(value)
            ReportPropertyChanging("ToteReachHeight")
            _ToteReachHeight = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("ToteReachHeight")
            OnToteReachHeightChanged()
        End Set
    End Property

    Private _ToteReachHeight As Global.System.Int16
    Private Partial Sub OnToteReachHeightChanging(value As Global.System.Int16)
    End Sub

    Private Partial Sub OnToteReachHeightChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property BinReachHeight() As Global.System.Int16
        Get
            Return _BinReachHeight
        End Get
        Set
            OnBinReachHeightChanging(value)
            ReportPropertyChanging("BinReachHeight")
            _BinReachHeight = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("BinReachHeight")
            OnBinReachHeightChanged()
        End Set
    End Property

    Private _BinReachHeight As Global.System.Int16
    Private Partial Sub OnBinReachHeightChanging(value As Global.System.Int16)
    End Sub

    Private Partial Sub OnBinReachHeightChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property TeamName() As Global.System.String
        Get
            Return _TeamName
        End Get
        Set
            OnTeamNameChanging(value)
            ReportPropertyChanging("TeamName")
            _TeamName = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("TeamName")
            OnTeamNameChanged()
        End Set
    End Property

    Private _TeamName As Global.System.String
    Private Partial Sub OnTeamNameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnTeamNameChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Runs() As Global.System.Int16
        Get
            Return _Runs
        End Get
        Set
            OnRunsChanging(value)
            ReportPropertyChanging("Runs")
            _Runs = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("Runs")
            OnRunsChanged()
        End Set
    End Property

    Private _Runs As Global.System.Int16
    Private Partial Sub OnRunsChanging(value As Global.System.Int16)
    End Sub

    Private Partial Sub OnRunsChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property LandfillLitterTotal() As Global.System.String
        Get
            Return _LandfillLitterTotal
        End Get
        Set
            OnLandfillLitterTotalChanging(value)
            ReportPropertyChanging("LandfillLitterTotal")
            _LandfillLitterTotal = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("LandfillLitterTotal")
            OnLandfillLitterTotalChanged()
        End Set
    End Property

    Private _LandfillLitterTotal As Global.System.String
    Private Partial Sub OnLandfillLitterTotalChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnLandfillLitterTotalChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property RecycledLitterTotal() As Global.System.Int16
        Get
            Return _RecycledLitterTotal
        End Get
        Set
            OnRecycledLitterTotalChanging(value)
            ReportPropertyChanging("RecycledLitterTotal")
            _RecycledLitterTotal = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("RecycledLitterTotal")
            OnRecycledLitterTotalChanged()
        End Set
    End Property

    Private _RecycledLitterTotal As Global.System.Int16
    Private Partial Sub OnRecycledLitterTotalChanging(value As Global.System.Int16)
    End Sub

    Private Partial Sub OnRecycledLitterTotalChanged()
    End Sub

    #End Region

    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("MyScout2015DBModel", "FK_EventsTableTeamTotalsTable", "EventsTable")>
    Public Property EventsTable() As EventsTable
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of EventsTable)("MyScout2015DBModel.FK_EventsTableTeamTotalsTable", "EventsTable").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of EventsTable)("MyScout2015DBModel.FK_EventsTableTeamTotalsTable", "EventsTable").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property EventsTableReference() As EntityReference(Of EventsTable)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of EventsTable)("MyScout2015DBModel.FK_EventsTableTeamTotalsTable", "EventsTable")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of EventsTable)("MyScout2015DBModel.FK_EventsTableTeamTotalsTable", "EventsTable", value)
            End If
        End Set
    End Property

    #End Region

End Class

#End Region


